# Generated by Django 3.2.7 on 2021-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('protector_check', models.BooleanField(default=False)),
                ('protector_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
