# Generated by Django 3.2.7 on 2021-10-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('pcode', models.CharField(max_length=20)),
                ('ppost', models.CharField(max_length=50)),
                ('paddress', models.CharField(max_length=100)),
                ('pphone', models.CharField(blank=True, max_length=20, null=True)),
                ('purl', models.CharField(blank=True, max_length=50, null=True)),
                ('plng', models.FloatField()),
                ('plat', models.FloatField()),
            ],
        ),
    ]
