# Generated by Django 3.2.7 on 2021-10-28 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local', '0002_pharmacyinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalinfo',
            name='hphone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='hospitalinfo',
            name='hurl',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pharmacyinfo',
            name='pphone',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='pharmacyinfo',
            name='purl',
            field=models.CharField(default='', max_length=50),
        ),
    ]
