# Generated by Django 3.2.7 on 2021-11-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=20)),
                ('morning', models.CharField(default='00 : 00', max_length=50)),
                ('afternoon', models.CharField(default='00 : 00', max_length=50)),
                ('evening', models.CharField(default='00 : 00', max_length=50)),
                ('morning_switch', models.BooleanField(default=False)),
                ('afternoon_switch', models.BooleanField(default=False)),
                ('evening_switch', models.BooleanField(default=False)),
            ],
        ),
    ]
