# Generated by Django 3.1.3 on 2020-11-15 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=20)),
                ('major', models.CharField(max_length=20)),
                ('minor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idx', models.IntegerField()),
                ('parent_id', models.IntegerField()),
                ('career', models.CharField(max_length=20)),
                ('number', models.IntegerField()),
                ('department', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IntroList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enterprise', models.CharField(max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('content', models.TextField(null=True)),
                ('video', models.TextField(null=True)),
                ('time', models.TextField(null=True)),
                ('count', models.TextField(null=True)),
                ('list', models.TextField(null=True)),
                ('title', models.TextField(null=True)),
                ('contents', models.TextField(null=True)),
                ('habitlist', models.TextField(null=True)),
                ('wordlist', models.TextField(null=True)),
                ('stt', models.TextField(null=True)),
                ('emotion', models.TextField(null=True)),
                ('emotionlist', models.TextField(null=True)),
                ('thumbnail', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=20)),
                ('eid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=50)),
                ('profile', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('major', models.CharField(max_length=20)),
                ('minor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hid', models.IntegerField()),
                ('word', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video', models.FileField(blank=True, null=True, upload_to='video/')),
                ('time', models.IntegerField(null=True)),
                ('first_iid', models.IntegerField(null=True)),
                ('second_iid', models.IntegerField(null=True)),
                ('third_iid', models.IntegerField(null=True)),
                ('fourth_iid', models.IntegerField(null=True)),
                ('fifth_iid', models.IntegerField(null=True)),
                ('sixth_iid', models.IntegerField(null=True)),
                ('first_sst', models.CharField(max_length=1000, null=True)),
                ('second_sst', models.CharField(max_length=1000, null=True)),
                ('third_sst', models.CharField(max_length=1000, null=True)),
                ('fourth_sst', models.CharField(max_length=1000, null=True)),
                ('fifth_sst', models.CharField(max_length=1000, null=True)),
                ('sixth_sst', models.CharField(max_length=1000, null=True)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbnail/')),
                ('uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=500)),
                ('writer', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('idx', models.IntegerField()),
                ('intro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.introlist')),
            ],
        ),
        migrations.CreateModel(
            name='MyChatting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cid', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('pos', models.IntegerField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.board')),
            ],
        ),
        migrations.CreateModel(
            name='Chatting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('writer', models.CharField(max_length=20)),
                ('contents', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('chatlist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.introlist')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('pos', models.IntegerField()),
                ('user_id', models.CharField(max_length=20)),
                ('intro_id', models.IntegerField()),
                ('department', models.CharField(max_length=50, null=True)),
                ('idx', models.IntegerField()),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.list')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
