# Generated by Django 3.2.7 on 2021-11-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawCalendar',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=20)),
                ('rawStringList', models.TextField(null=True)),
            ],
        ),
    ]
